const QUESTIONS = {
  level1: {
    name: "Perception",
    color: "#9B59B6",
    colorLight: "#C39BD3",
    subtitle: "How well do you really see me?",
    cards: [
      "What do you think I'm most insecure about?",
      "What's something I pretend to like but actually don't?",
      "What do you think I'd change about myself if I could?",
      "What habit of mine do you secretly find adorable?",
      "If I could have any career with guaranteed success, what do you think I'd choose?",
      "What's the first thing you noticed about me that wasn't physical?",
      "What do you think keeps me up at night?",
      "What song do you think describes me perfectly?",
      "What do you think my love language actually is, even if I say otherwise?",
      "What's something I do when I'm nervous that I probably don't realize?",
      "What topic could I talk about for hours without getting bored?",
      "What do you think I need more of in my life right now?",
      "How do you think I handle disappointment when no one's watching?",
      "What do you think my biggest strength is in this relationship?",
      "If you had to describe me in three words to a stranger, which three?",
      "What do you think I was like as a teenager?",
      "What do you think I'm most proud of about myself?",
      "What's something small that you know makes my entire day better?",
      "What do you think I wish more people understood about me?",
      "What do you think I value more — being respected or being loved?",
      "How do you think I'd react if you told me something you've been holding back?",
      "What do you think is my go-to coping mechanism?",
      "What would I most likely be late to and why?",
      "How do you think I feel about where I am in life right now?",
      "What's something you think I've outgrown but haven't let go of yet?",
      "What movie character do you think I relate to most?",
      "What do you think I daydream about?",
      "What part of my personality do you think I underestimate?",
      "How do you think I show love when I don't say it out loud?",
      "What's an opinion I hold that you think will never change?",
      "What do you think I need to hear more often?",
      "When do you think I feel most like myself?",
      "What do you think I'd do if I had one week completely alone?",
      "What's something about me you figured out before I told you?",
      "What do you think stresses me out more than it should?",
      "How do you think I'd describe this relationship to my closest friend?",
      "What do you think I fake being okay about?",
      "What childhood experience do you think shaped me the most?",
      "What do you think I find most attractive about you — and be honest?",
      "What's something you think I still need to learn?",
      "What do you think I'm most afraid of losing?",
      "What's a compliment you think I secretly want but never ask for?",
      "What do you think I look like when I'm deep in thought?",
      "What was your first impression of me, and how wrong were you?",
      "What do you think I'd spend money on if price didn't matter?",
      "What do you think my guilty pleasure is?",
      "How do you think I act around people I'm uncomfortable with?",
      "What do you think my biggest regret is?",
      "If I wrote a book, what do you think it would be about?",
      "What do you think I'd want my legacy to be?"
    ]
  },

  level2: {
    name: "Connection",
    color: "#E67E22",
    colorLight: "#F0B27A",
    subtitle: "The questions we never think to ask.",
    cards: [
      "What's something you've never told me because you didn't know how I'd react?",
      "When was the last time I made you feel truly seen?",
      "What's a fear you have about us that you've never said out loud?",
      "What part of your past are you still healing from?",
      "When do you feel most disconnected from me, and what could I do differently?",
      "What's something I do that makes you feel safe?",
      "Is there a version of yourself you're afraid to show me? Why?",
      "What's something you wish you could forgive yourself for?",
      "When was the last time you cried and what triggered it?",
      "What's the hardest thing about loving me?",
      "What do you need from me that you've stopped asking for?",
      "What's a small moment between us that meant more to you than I probably realize?",
      "How has being with me changed the way you see yourself?",
      "What's a boundary you need me to respect better?",
      "What emotion is the hardest for you to express, and why?",
      "When did you first realize this was more than just attraction?",
      "What's something about your parents' relationship that you're afraid of repeating?",
      "Tell me about a time you felt lonely even though we were together.",
      "What do you wish I'd ask you about more often?",
      "What's a promise you've made to yourself about how you'll love?",
      "What's the most vulnerable you've ever felt with me?",
      "If you could change one pattern in how we argue, what would it be?",
      "What's a dream you've quietly let go of, and do you miss it?",
      "When do you feel like you have to perform instead of just being yourself around me?",
      "What's something you admire about me that has nothing to do with how I treat you?",
      "What scares you most about getting closer to someone?",
      "What's one thing I could do this week that would make you feel more loved?",
      "How do you want to be comforted when you're going through something hard?",
      "What's a truth about yourself that you've only recently accepted?",
      "When was the last time you felt proud of us?",
      "What's something you hold back from saying because you don't want to seem needy?",
      "What part of loving someone have you had to learn the hard way?",
      "Is there something you've been wanting to apologize for?",
      "What's the kindest thing someone has ever done for you?",
      "What would it take for you to fully trust someone with everything?",
      "What's something about yourself that you want me to be more patient with?",
      "How do you know when you're falling out of love, and does that scare you?",
      "What's a conversation we keep having that you wish we could finally resolve?",
      "Tell me something you think about often but never bring up.",
      "What does home feel like to you, and do you feel it with me?",
      "What's something you pretend doesn't bother you, but it does?",
      "What's a lie you told me early on that you wish you could take back?",
      "What do you think we avoid talking about?",
      "If you could hear one thing from me right now, what would it be?",
      "What's a part of me you fell in love with that I don't show enough anymore?",
      "What's the loneliest you've ever felt in your life?",
      "What are you still learning about yourself?",
      "What do you think we're both pretending is fine?",
      "When did you last feel truly at peace, and where was I?",
      "What's a wound you carry that you haven't let me help with?"
    ]
  },

  level3: {
    name: "Reflection",
    color: "#3498DB",
    colorLight: "#85C1E9",
    subtitle: "Where we've been. Where we're going.",
    cards: [
      "What has this relationship taught you about yourself that nothing else could?",
      "What's one thing you want us to never stop doing?",
      "How have you grown since we've been together?",
      "What's a hard season we went through that actually made us stronger?",
      "If you could relive one moment with me, which would you choose?",
      "What's something I've helped you believe about yourself?",
      "What do you think our biggest test as a couple will be?",
      "What kind of old couple do you want us to be?",
      "What's the most important thing I've taught you about love?",
      "What do you want to build together that we haven't started yet?",
      "What's something you'd do differently if we were starting over?",
      "What part of yourself have you discovered because of us?",
      "When do you feel most grateful for this relationship?",
      "What's a small tradition or habit you want us to create?",
      "How do you want us to handle it when things get really hard?",
      "What's one thing about me you hope never changes?",
      "What does growing old together look like in your mind?",
      "What's something you want to experience with me before the year is over?",
      "What have I given you that you didn't know you needed?",
      "What's the bravest thing you've done in this relationship?",
      "If our relationship had a thesis statement, what would it be?",
      "What does unconditional love mean to you, and do you think it's possible?",
      "What's one thing you want to protect about us as we change over time?",
      "How do you want me to love you differently five years from now?",
      "What's a sacrifice you've made for us that you'd make again without hesitating?",
      "What truth about love do you know now that you didn't before me?",
      "What's the greatest risk you've taken for this relationship?",
      "What do you think is the secret to making this last?",
      "What's one promise you want to make to me right now?",
      "Tell me something you want me to remember on the days when things feel hard.",
      "What's something we haven't done together that would bring us closer?",
      "How do you want to be remembered by me?",
      "What do you think we'll laugh about in ten years?",
      "What's the most important lesson love has taught you so far?",
      "If we could start a new chapter tomorrow, what would you title it?",
      "What's something you want to let go of so we can move forward?",
      "What would you fight for — even when it's hard — to keep us together?",
      "What part of our story do you hope never gets forgotten?",
      "What's the most honest thing you can say about where we are right now?",
      "What do you want the last thing you ever say to me to be?"
    ]
  },

  bonus: {
    name: "36 Questions",
    color: "#E84393",
    colorLight: "#FD79A8",
    subtitle: "The famous experiment proven to create closeness.",
    description: "In 1997, psychologist Arthur Aron published a study that made strangers fall in love in a lab using 36 questions. These are those questions — adapted for two people who already chose each other.",
    cards: [
      "Given the choice of anyone in the world, whom would you want as a dinner guest?",
      "Would you like to be famous? In what way?",
      "Before making a phone call, do you ever rehearse what you are going to say? Why?",
      "What would constitute a perfect day for you?",
      "When did you last sing to yourself? To someone else?",
      "If you were able to live to the age of 90 and retain either the mind or body of a 30-year-old for the last 60 years of your life, which would you want?",
      "Do you have a secret hunch about how you will die?",
      "Name three things you and your partner appear to have in common.",
      "For what in your life do you feel most grateful?",
      "If you could change anything about the way you were raised, what would it be?",
      "Take four minutes and tell your partner your life story in as much detail as possible.",
      "If you could wake up tomorrow having gained any one quality or ability, what would it be?",
      "If a crystal ball could tell you the truth about yourself, your life, the future, or anything else, what would you want to know?",
      "Is there something that you've dreamed of doing for a long time? Why haven't you done it?",
      "What is the greatest accomplishment of your life?",
      "What do you value most in a friendship?",
      "What is your most treasured memory?",
      "What is your most terrible memory?",
      "If you knew that in one year you would die suddenly, would you change anything about the way you are now living? Why?",
      "What does friendship mean to you?",
      "What roles do love and affection play in your life?",
      "Alternate sharing something you consider a positive characteristic of your partner. Share a total of five items each.",
      "How close and warm is your family? Do you feel your childhood was happier than most other people's?",
      "How do you feel about your relationship with your mother?",
      "Make three true 'we' statements each. For instance, 'We are both in this room feeling...'",
      "Complete this sentence: 'I wish I had someone with whom I could share...'",
      "If you were going to become a close friend with your partner, please share what would be important for them to know.",
      "Tell your partner what you like about them. Be very honest, saying things that you might not say to someone you've just met.",
      "Share with your partner an embarrassing moment in your life.",
      "When did you last cry in front of another person? By yourself?",
      "Tell your partner something that you like about them already.",
      "What, if anything, is too serious to be joked about?",
      "If you were to die this evening with no opportunity to communicate with anyone, what would you most regret not having told someone? Why haven't you told them yet?",
      "Your house, containing everything you own, catches fire. After saving your loved ones and pets, you have time to safely make a final dash to save any one item. What would it be? Why?",
      "Of all the people in your family, whose death would you find most disturbing? Why?",
      "Share a personal problem and ask your partner's advice on how they might handle it. Also, ask your partner to reflect back to you how you seem to be feeling about the problem you have chosen."
    ]
  },

  spicy: {
    name: "After Dark",
    color: "#C0392B",
    colorLight: "#E74C3C",
    subtitle: "For when the lights go down.",
    cards: [
      "What's something you've always wanted to try with me but haven't asked?",
      "Describe the exact moment you first felt physically drawn to me.",
      "What's the most attractive thing I do without realizing it?",
      "If tonight were only about us — no plans, no distractions — what would you want?",
      "What's a fantasy you've never shared with anyone?",
      "Where is your favorite place for me to touch you?",
      "What's the most romantic thing I've ever done for you?",
      "How do you want to be kissed right now?",
      "What outfit or look of mine drives you the most crazy?",
      "When do you want me most?",
      "What does desire feel like to you? Describe the physical sensation.",
      "What's something small I do that unexpectedly turns you on?",
      "If you could design our perfect evening from start to finish, what would it look like?",
      "What part of my body do you find most beautiful?",
      "Describe a dream you've had about me.",
      "What makes you feel most desired?",
      "What's the boldest romantic gesture you wish you had the courage to make?",
      "If we could escape anywhere for 48 hours alone, where and why?",
      "What scent or smell instantly reminds you of being close to me?",
      "What song makes you think of us in an intimate way?",
      "What's something I whisper that gives you chills?",
      "When was the last time you looked at me and felt your heart race?",
      "What does passion mean to you in a relationship?",
      "What's a boundary you'd like to explore together?",
      "How do you know when I'm in the mood without me saying anything?",
      "What's the most vulnerable moment we've shared physically?",
      "What three words would you use to describe our chemistry?",
      "What's something I've done that made you feel irresistible?",
      "If you could freeze one intimate moment between us in time, which would it be?",
      "What do you want more of from me physically?"
    ]
  },

  anniversary: {
    name: "Our Story",
    color: "#D4A853",
    colorLight: "#F1C40F",
    subtitle: "Celebrating every chapter of us.",
    cards: [
      "What's your favorite 'how we met' detail that other people don't know?",
      "What moment made you think 'I want to spend my life with this person'?",
      "What's the hardest thing we've overcome together?",
      "What's a tiny moment between us that you replay in your mind?",
      "How have I surprised you since we've been together?",
      "What's the most important lesson our relationship has taught you?",
      "What do you remember about our first date that I've probably forgotten?",
      "What milestone of ours are you most proud of?",
      "If you could write a letter to yourself on the day we met, what would you say?",
      "What's something about us that's gotten better with time?",
      "What do you think future us will be like in 10 years?",
      "What's your favorite tradition or inside joke we share?",
      "What moment made you realize you were in love with me?",
      "What's the best adventure we've had together?",
      "What's a quality of mine that you've come to appreciate more over time?",
      "What do you want to tell me that you haven't found the right moment for?",
      "What part of our early days do you miss the most?",
      "What's the most meaningful gift or gesture you've received from me?",
      "What's one thing about our relationship that makes it different from any other?",
      "When did you last feel truly proud of us as a couple?",
      "What's a challenge we faced that ended up bringing us closer?",
      "What do you hope we never forget about how we started?",
      "What's something new you've discovered about yourself through loving me?",
      "What would you tell our future selves about how we made it work?",
      "What does partnership mean to you after being with me?",
      "What year or season of our relationship has been your favorite so far?",
      "What's the best piece of advice someone gave you about love that actually came true with us?",
      "What moment in our relationship felt like a turning point?",
      "If our love story were a movie, what would the title be?",
      "What do you want the next chapter of our story to look like?"
    ]
  },

  wildcards: [
    { type: "action", text: "Hold both of your partner's hands and make eye contact for 30 seconds without speaking.", timer: 30 },
    { type: "action", text: "Each of you name three things you find beautiful about the other person. Go back and forth." },
    { type: "action", text: "Trade phones for 60 seconds. No rules about what you look at.", timer: 60 },
    { type: "action", text: "Slow dance together for one full song. No talking. Pick the song together." },
    { type: "action", text: "Write down your favorite memory together on a piece of paper. Read them out loud at the same time." },
    { type: "action", text: "Close your eyes. Describe what your partner is wearing right now in full detail." },
    { type: "action", text: "Give your partner the compliment you've been thinking but haven't said." },
    { type: "action", text: "Let your partner scroll through your camera roll for 30 seconds. Explain any photo they ask about.", timer: 30 },
    { type: "action", text: "Hug for 20 seconds. No talking. Just be there.", timer: 20 },
    { type: "action", text: "Each say one thing you want to leave behind and one thing you want to carry forward in this relationship." },
    { type: "action", text: "Look at each other and say 'I'm grateful for you because...' — complete the sentence without thinking too hard." },
    { type: "action", text: "Put on a song that reminds you of your partner. Explain why." },
    { type: "action", text: "Take turns finishing this sentence: 'I feel closest to you when...'"},
    { type: "action", text: "Each person shares their lock screen. What does it say about you?" },
    { type: "action", text: "Recreate your first kiss. Or try to. Laughing counts." },
    { type: "action", text: "Set a timer for 2 minutes. Say everything you appreciate about your partner without stopping.", timer: 120 },
    { type: "action", text: "Show your partner the last 5 people you texted. Tell them something about each one." },
    { type: "action", text: "Take a selfie together right now. No retakes. Keep it." },
    { type: "action", text: "Each write down one word that describes how you feel right now. Share at the same time." },
    { type: "action", text: "Give your partner a 30-second shoulder massage. No talking. Just presence.", timer: 30 }
  ],

  digDeeper: [
    "I feel like there's more. Go deeper.",
    "That was safe. What's the real answer?",
    "Say the version of that you'd tell your best friend.",
    "You're holding back. I want the unfiltered version.",
    "Close your eyes. Now answer that again, honestly.",
    "What's the part of that answer you almost didn't say?",
    "I love you. Now tell me the truth.",
    "Forget how it sounds. What do you actually feel?",
    "Pretend I can't be hurt by the answer. Now say it.",
    "That was the headline. Give me the full story.",
    "What would you say if you weren't afraid of my reaction?",
    "That answer protected you. What answer would protect us?",
    "You answered with your head. Answer with your chest.",
    "If this were the last time we ever talked about this, what would you actually say?",
    "Say it like you mean it. Not like you rehearsed it."
  ],

  finalCard: {
    prompts: [
      "Write your partner a note. Say something you've been meaning to say, something you're afraid to say, or something you want them to carry with them. Fold it. Exchange them. Open it later — not now. Let it find you when you need it.",
      "Look into each other's eyes for four minutes. No talking. No looking away. Just be present. When it's over, say one thing you felt.",
      "Each of you write down three things you've never said to the other person. Exchange papers. Read them in silence. Then talk.",
      "Make one promise to each other right now — not about forever, just about tomorrow. Something small. Something real.",
      "Take turns completing this sentence five times each: 'I love you because...' Don't think. Just say it.",
      "Write down your favorite memory together on separate pieces of paper. Read them out loud. Keep them somewhere you'll find them later.",
      "Tell your partner the exact moment you knew. They'll know what you mean."
    ]
  }
};
